// First, so a compiled engine older than its source refuses before anything
// else of it runs. fresh-build.ts says why.
import './fresh-build.js';

export type {
  AppUnderTest,
  Candidate,
  Exclusions,
  ExclusionGroup,
  StalenessGuard,
  Narrowing,
  UniversalCheck,
  AppCheck,
  AppCheckContext,
  AppCheckVerdict,
  LogPath,
} from './app-under-test.js';
export { UNIVERSAL_CHECKS } from './app-under-test.js';
export {
  resolveBundle,
  assertBundleFresh,
  allowStaleFromEnvironment,
  ALLOW_STALE_VARIABLE,
  type ResolvedBundle,
  type GuardVerdict,
} from './bundle.js';
export {
  launchApp,
  closeApp,
  reloadRenderer,
  makeUserDataDir,
  runTempFolder,
  TEMP_FOLDER_VARIABLE,
  removeProfile,
  DEFAULT_PROFILE_WATCH_MS,
  hideWindows,
  reachMainProcess,
  MAIN_PROCESS_ATTEMPTS,
  showWindows,
  windowMode,
  prepareWindows,
  activateWindows,
  WINDOW_MODE_VARIABLE,
  requireAppDir,
  APP_DIR_VARIABLE,
  type WindowMode,
  UNAVAILABLE_UNDER,
  type LaunchedApp,
  type LaunchPath,
} from './launch.js';
export { createTest, expect, rendererVerdict, screenshotWithin, type PhileasFixtures } from './fixtures.js';
export {
  clickMenuItem,
  menuLabels,
  menuEntries,
  type MenuEntry,
} from './menu.js';
export {
  stubOpenExternal,
  openedExternally,
  clearOpenExternal,
  stubOpenPaths,
  openedPaths,
  stubSelfLaunch,
  selfLaunches,
} from './external.js';
export { caughtSince, type CaughtByStubs } from './caught.js';
export { stubNativeDialogs, nativeDialogs, type NativeDialogCall } from './dialogs.js';
export { endStrayProcesses, type StrayReport } from './strays.js';
export {
  defineJourney,
  routeNumbers,
  SHORTEST_DEADLINE_MS,
  playwrightTimeouts,
  resolveSeed,
  requireSeed,
  generateSeed,
  SEED_VARIABLE,
  resolveRun,
  OVERRIDE_VARIABLES,
  FIX_OVERRIDE_VARIABLE,
  overriddenTerms,
  requireRun,
  RUN_VARIABLE,
  type Journey,
  type JourneyTerms,
} from './journey.js';
export { startJourney, finishJourney, runEveryCheck, startTempFolder, ALLOW_TEMP_LEFTOVERS_VARIABLE } from './start.js';
export { staleSources, requireFreshBuild, ALLOW_STALE_BUILD_VARIABLE } from './fresh-build.js';
export {
  guardHome,
  snapshotHome,
  readHome,
  writesSince,
  outsideCopies,
  ALLOW_HOME_WRITES_VARIABLE,
  type GuardedApplication,
  type HomeSnapshot,
  type HomeReading,
  type JourneyFolder,
} from './home-guard.js';
export { defineFixes, fixFor, fixName, NO_FIX, type Fixes } from './fixes.js';
export {
  signatureOf,
  refuseUnfitVarying,
  findingId,
  readKnownFindings,
  markFiled,
  dismissFinding,
  removeFinding,
  currentSignature,
  resignKnownFindings,
  findingsInRun,
  recordJourneyFindings,
  renderJourneyFindings,
  type KnownFinding,
  type KnownFindings,
  type JourneyFindings,
} from './known.mjs';
export {
  createRng,
  deriveRouteSeed,
  deriveRouteStreams,
  type Rng,
  type RouteStreams,
} from './random.js';
export {
  survey,
  takesTypedValue,
  printedShortcut,
  COMMON_KEYS,
  type KeyCandidate,
  toCandidate,
  createExclusionTally,
  neverMatched,
  allowedGroupsFromEnvironment,
  ALLOW_EXCLUDED_VARIABLE,
  NondeterministicExclusion,
  ApplicationStoppedAnswering,
  HOPPABLE_ROLES,
  type SurveyedCandidate,
  type PageCandidate,
  type MenuCandidate,
  type SurveyResult,
  type MenuSourceVerdict,
  type UnnamedElement,
  type ExcludedCandidate,
  type ExclusionTally,
} from './survey.js';
export {
  Journal,
  readJournal,
  journalPath,
  journalFolder,
  type JournalEntry,
  type OpeningEntry,
  type PoolEntry,
  type FixStepEntry,
  type TripHopEntry,
  type HopAction,
  type NoteEntry,
  type ClosingEntry,
  type JournaledCandidate,
  type JournaledCheck,
} from './journal.js';
export { effectOf, headingsIn, EFFECT_HEADINGS_LISTED, type HopEffect } from './effect.js';
export {
  runRoute,
  settle,
  DEFAULT_SETTLE_QUIET_MS,
  hopDelayFromEnvironment,
  HOP_DELAY_VARIABLE,
  FOLLOW_VARIABLE,
  SURVEY_VARIABLE,
  surveyFromEnvironment,
  surveyLines,
  followFromEnvironment,
  seededChooser,
  DEFAULT_KEY_SHARE,
  DEFAULT_MENU_SHARE,
  sharesFor,
  createSeededChooser,
  drawMenuByLevel,
  type Shares,
  sideOfShareDraw,
  sideCandidates,
  keepsRouteGoing,
  type Side,
  isCommonKey,
  seededValues,
  FixFailure,
  PageUnreachable,
  type Chooser,
  type Choice,
  type ValueGenerator,
  type Fix,
  type FixContext,
  type FixStep,
  type RouteOutcome,
  type RunRouteOptions,
} from './route.js';
export {
  startWatching,
  failedChecks,
  showsNothing,
  CheckFailure,
  AdapterCheckError,
  PageConnectionLost,
  assertAppChecks,
  CHECK_ORDER,
  LOG_FAILURE,
  TRACE_SNAPSHOT_IN_SANDBOX,
  DEFAULT_RESPONSIVE_TIMEOUT_MS,
  STALLED,
  judgedByTheWatch,
  rendererObservation,
  type Watch,
  type WatchOptions,
} from './oracles/index.js';
export { renderEntry, renderJournal, effectText, targetText, shortened } from './report/render.mjs';
